# Generated by Django 5.1.1 on 2024-09-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flow',
            table='flow',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
