# Generated by Django 5.1.1 on 2024-09-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_flow_table_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
