# Generated by Django 5.1.1 on 2024-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_senha_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='user',
            new_name='id_user',
        ),
        migrations.AlterField(
            model_name='flow',
            name='estatus',
            field=models.CharField(max_length=1),
        ),
    ]
