# Generated by Django 5.1.1 on 2024-10-08 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='coast',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
    ]
