# Generated by Django 5.1.1 on 2024-10-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_accounts_id_user_alter_accounts_coast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
